language: java

jdk:
  - oraclejdk8

install:
  - git clone --depth=1 -b matrix https://github.com/STAMP-project/pitest
  - cd pitest
  - mvn install -DskipTests
  - cd ..

after_success:
  - mvn clean test jacoco:report coveralls:report
